[package]
name = "libssh-cli-demo"
version = "0.1.0"
edition = "2024"

[dependencies]
clap     = { version = "4", features = ["derive"] }
anyhow   = "1"
rpassword = "7"

[build-dependencies]
bindgen    = "0.71"
pkg-config = "0.3"
